name: zapp_entry_bug
description: Bug Reproduction Code.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
